### ISSUE TITLE
Why is Pandas <2 required?

### ISSUE THREAD

**Issue by nosalorenz** [crypto-lake/lake-api#4] opened 2023-10-02 10:16 UTC
* Lake API version: 0.8.0
* Python version: 3.10
* Operating System: macOS, Ubuntu

### Description

I want to install lake API with a Pandas version greater than 2.0.0.
Why is lake api restricting pandas version to <2?

### What I Did

Just installing requirements as follows:
```
pandas >= 2.1.0
lakeapi
```

**Comment by leftys** [comment] 2023-10-02 10:56
Hi @nosalorenz, this is caused by one of our dependencies awswrangler that also depends on pandas. We knew about this issue, but we will increase its priority and hopefully remove the <2 constraint within a few days to solve your issues.

**Comment by nosalorenz** [comment] 2023-10-02 11:49
Hi, thanks for the fast answer. I see the problem. I hope you are able to move to the new awswrangler version as soon as possible.

**Comment by nosalorenz** [comment] 2023-10-31 15:36
Hi, are there any news on this?

**Comment by leftys** [comment] 2023-11-03 11:59
Hi @nosalorenz, I just released lakeapi==0.9.1 that should remove awswrangler dependency completely. Check it out and let me know if I can close this, it worked well with latest Pandas version for me plus removed a lot of indirect dependencies from our code.

There are some ugly temporary workarounds there as we would like to move away from direct s3 access completely, but my efforts in this direction were not successful yet.

**Closed** 2023-11-15 10:13 UTC
